include: 
  - infra.local.yaml

services:
  room-environment-monitor-listener:
    build: kevinlutzer/room-environment-monitor-listener:local
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb
      - mosquitto
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
      - HOST=0.0.0.0
      - PORT=8080
      - DATABASE_URL=postgres://postgres:mysecretpassword@localhost:5432/postgres
    networks:
      - backend
