name: BuildAndCheck

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # Build, test, lint and format check the code
    - name: Build
      run: cargo build --verbose
    
    - name: Run tests
      run: cargo test --verbose

    - name: Run format check
      run: cargo fmt --check

    - name: Run clippy
      run: cargo clippy --no-deps -- -D warnings
